// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLLcLJ-CQq3I0gY95vROwiSHMA1cd2_NM',
    appId: '1:904574115748:web:ca2c749869cd7040532b31',
    messagingSenderId: '904574115748',
    projectId: 'notes-21271',
    authDomain: 'notes-21271.firebaseapp.com',
    storageBucket: 'notes-21271.firebasestorage.app',
    measurementId: 'G-0819F0Z09Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeuBftp-nOdsvEBh2nDRcGc_hllQ8U_T8',
    appId: '1:904574115748:android:16118175660a6a36532b31',
    messagingSenderId: '904574115748',
    projectId: 'notes-21271',
    storageBucket: 'notes-21271.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcAzYlLg2tqU-fAeWmmr4mc5aA7eeOjwM',
    appId: '1:904574115748:ios:97514729fd687dd4532b31',
    messagingSenderId: '904574115748',
    projectId: 'notes-21271',
    storageBucket: 'notes-21271.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcAzYlLg2tqU-fAeWmmr4mc5aA7eeOjwM',
    appId: '1:904574115748:ios:97514729fd687dd4532b31',
    messagingSenderId: '904574115748',
    projectId: 'notes-21271',
    storageBucket: 'notes-21271.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLLcLJ-CQq3I0gY95vROwiSHMA1cd2_NM',
    appId: '1:904574115748:web:596d15427e48b2d8532b31',
    messagingSenderId: '904574115748',
    projectId: 'notes-21271',
    authDomain: 'notes-21271.firebaseapp.com',
    storageBucket: 'notes-21271.firebasestorage.app',
    measurementId: 'G-4QLVJ5R2P2',
  );
}
