// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp9-jfGXwmqeguYxpto7yEcP47WRZyJfc',
    appId: '1:553677488597:web:8847d82e224c5e72217d5c',
    messagingSenderId: '553677488597',
    projectId: 'daftarbelanja-42e3f',
    authDomain: 'daftarbelanja-42e3f.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-42e3f-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-42e3f.firebasestorage.app',
    measurementId: 'G-YEGETQP57J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_c-8-8yBX6Ar4dCaZu1r4GTbchcS-1L4',
    appId: '1:553677488597:android:7974a9a6dc9fe63e217d5c',
    messagingSenderId: '553677488597',
    projectId: 'daftarbelanja-42e3f',
    databaseURL: 'https://daftarbelanja-42e3f-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-42e3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOJKZR8v_PrLt7wqzDplhnPk2wGWr8Qfw',
    appId: '1:553677488597:ios:68adb726e96f10e2217d5c',
    messagingSenderId: '553677488597',
    projectId: 'daftarbelanja-42e3f',
    databaseURL: 'https://daftarbelanja-42e3f-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-42e3f.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOJKZR8v_PrLt7wqzDplhnPk2wGWr8Qfw',
    appId: '1:553677488597:ios:68adb726e96f10e2217d5c',
    messagingSenderId: '553677488597',
    projectId: 'daftarbelanja-42e3f',
    databaseURL: 'https://daftarbelanja-42e3f-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-42e3f.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp9-jfGXwmqeguYxpto7yEcP47WRZyJfc',
    appId: '1:553677488597:web:0f4ca9359cc394f7217d5c',
    messagingSenderId: '553677488597',
    projectId: 'daftarbelanja-42e3f',
    authDomain: 'daftarbelanja-42e3f.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-42e3f-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-42e3f.firebasestorage.app',
    measurementId: 'G-LC4LDPENZ2',
  );
}
