// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARdf6zFDJAEmy3yVaR18suEDh_HsSsiuw',
    appId: '1:107588614148:web:d1b0da7b3eafc8d5751d51',
    messagingSenderId: '107588614148',
    projectId: 'mdpgold-76fa0',
    authDomain: 'mdpgold-76fa0.firebaseapp.com',
    databaseURL: 'https://mdpgold-76fa0-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-76fa0.firebasestorage.app',
    measurementId: 'G-CCB91Y7SP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD638jxwMm7uG7csN_f4rYqvqOekM3jjFs',
    appId: '1:107588614148:android:22f403a7f4764008751d51',
    messagingSenderId: '107588614148',
    projectId: 'mdpgold-76fa0',
    databaseURL: 'https://mdpgold-76fa0-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-76fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO61kd2RfiK5DUNVLamYSPlQ70b5wEBPE',
    appId: '1:107588614148:ios:d1dceba0e5637f1d751d51',
    messagingSenderId: '107588614148',
    projectId: 'mdpgold-76fa0',
    databaseURL: 'https://mdpgold-76fa0-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-76fa0.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO61kd2RfiK5DUNVLamYSPlQ70b5wEBPE',
    appId: '1:107588614148:ios:d1dceba0e5637f1d751d51',
    messagingSenderId: '107588614148',
    projectId: 'mdpgold-76fa0',
    databaseURL: 'https://mdpgold-76fa0-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-76fa0.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARdf6zFDJAEmy3yVaR18suEDh_HsSsiuw',
    appId: '1:107588614148:web:013949ad48dfde5c751d51',
    messagingSenderId: '107588614148',
    projectId: 'mdpgold-76fa0',
    authDomain: 'mdpgold-76fa0.firebaseapp.com',
    databaseURL: 'https://mdpgold-76fa0-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-76fa0.firebasestorage.app',
    measurementId: 'G-R9PGTS4JQL',
  );
}
